### PR TITLE
Zach Teutsch multiples filter

### PR DESCRIPTION
**Pull request by spookyaction8**
check out my code guy

### CODE REVIEW

**Review by hayu4998 — APPROVED** [review]

**Review by Alder9 — APPROVED** [review]
Code compiles, runs, and works as intended. Some potential changes could be avoid using namespace std and just use the namespace in line like std::vector<int> v, for example.

**Review by PwnIn — COMMENTED** [review]
std::vector is more better than using namespace std

**Comment by PwnIn** [comment]
std::vector is more better than using namespace std

**Review by PwnIn — APPROVED** [review]

**Review by muzny — CHANGES_REQUESTED** [review]
remove my-new-branch-file, remove binary files

**Review by muzny — APPROVED** [review]

**Pull request merged**
