### PR TITLE
Adding Sign Function

### PR DESCRIPTION
**Pull request by nivo2247**
Nick Vomund and Garrett Hempy's implementation of Sign function.

### CODE REVIEW

**Comment by mattcohen1326** [comment]
Great Job guys, no changes needed.  What beautiful code

**Comment by algon96** [comment]
It worked how it's supposed to

**Comment by algon96** [comment]
It worked as it should. Good job.

**Review by muzny — APPROVED** [review]
Please resolve conflicts and merge into master by 2/19.

**Pull request merged**
