### PR TITLE
Zihan jun dongyu even mask

### PR DESCRIPTION
**Pull request by WinterDawn**

### CODE REVIEW

**Comment by jadkins89** [comment]
1. Function declaration needs a proper comment describing what the function does, return type and params.
    - Vector library is included in header file as well as cpp file.
2. The code compiles and runs, the output from main doesn't provide good intuition on if it ran correctly though
3. The code is appropriate for the repository
4. The style matches that of the repository
5. With further comments, the code appears to do what is attend to and is tested well.

**Comment by antonm1** [comment]
-There are no function comments to explain what this function is supposed to do
-Naming conventions in main() are slightly unclear
-The function was tested, but tests would be unclear without context (such as making the output given in main() write the number being tested next to the result of the test)
-<Main 14> calls EvenMask on bit again rather than the newly created bit_1, resulting in slightly unexpected behavior.
-The function appears to be written correctly despite what is written above.

**Review by muzny — CHANGES_REQUESTED** [review]
Please update the things that the other reviewers have requested by class 2/19.

**Review by muzny — APPROVED** [review]

**Comment by Jun1Sheng** [comment]
close pull requests

**Pull request closed without merging**
