### PR TITLE
VectorTimesN Pull Request

### PR DESCRIPTION
**Pull request by hainsworth99**
Finished the VectorTimesN function. Please review!

### CODE REVIEW

**Review by scarolac — APPROVED** [review]

**Review by scarolac — COMMENTED** [review]
Need to test function in main

**Review by scarolac — COMMENTED** [review]
Is the code understandable? no comments, variable names could be better than single characters
    Does it compile? Does it run as it should? It runs as it should
    Make sure there aren't "bad" files being added: No binaries present
    Is the code adequately tested? Single test in main

**Review by scarolac — APPROVED** [review]

**Review by intra-galactic — APPROVED** [review]
Everything's working

**Review by muzny — CHANGES_REQUESTED** [review]
remove my-new-branch-file by class 2/19

**Comment by hainsworth99** [comment]
Removed my-new-branch file, Travis CI test pass, should be good to go.

**Review by muzny — APPROVED** [review]

**Pull request merged**
