### PR TITLE
Zhou Yuan Alder

### PR DESCRIPTION
**Pull request by hayu4998**
Join all strings in a vector together, using the glue string in between them:
std::string Join(std::vector<std::string> pieces, std::string glue);

### CODE REVIEW

**Comment by KyleVanMeter** [comment]
The function works.  Other than some small style inconsistencies everything is fine.

**Review by spookyaction8 — COMMENTED** [review]
Code looks good and produces desired functionality. Compiles and runs. Remove .o and executable file.

**Review by muzny — CHANGES_REQUESTED** [review]
remove my-new-branch-file and binary files by class 2/19.

**Comment by muzny** [comment]
Remove the binary files (ManyFunctions.o and main) and fix the merge conflicts in main.cpp!

**Comment by muzny** [comment]
Make sure that your code is building!

**Review by muzny — APPROVED** [review]
Make sure your code is building then your are good to go!

**Comment by Alder9** [comment]
The code builds with JupyterLab, but doesn't work Travis. I think this might be because Travis is compiling with C++98 where as this works with C++11.

**Comment by PwnIn** [comment]
Have you take a look in the Travis terminal ? I think there are some mistakes that we have to fix?

**Comment by Alder9** [comment]
Both errors are the vector declarations in ManyFunctions.cpp which work for C++11 but not C++98. For some reason, Travis isn't applying the "-std=c++11" flag that's in the Makefile though it's there when I build in JupyterLab.

**Comment by Alder9** [comment]
@muzny I accidently merged without seeing your comment about it making sure it builds. I fixed the issue which I believe was the reason why it didn't build in the Makefile. Should I open another pull request for this fix?

**Pull request merged**
