### PR TITLE
Nickz joe derek sum

### PR DESCRIPTION
**Pull request by nzimmermann**
We implemented int Sum(std::vector<int> nums)  which takes a vector and returns the sum

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Compiles and runs fine with expected output. Did not include function comments in .cpp or a file comment in main.cpp.  Also not supposed to commit executables (a.out). Otherwise fine.

**Review by qlychee — DISMISSED** [review]
improve code understandability: add comments

**Review by AK-Ultra — COMMENTED** [review]
Warning thrown at for loop (signed to unsigned comparison): 
- change int i -> size_t i

**Review by muzny — CHANGES_REQUESTED** [review]
remove using namespace std by class 2/19

**Review by muzny — APPROVED** [review]

**Pull request merged**
