### PR TITLE
Product Function

### PR DESCRIPTION
**Pull request by adamtenhoeve**
Function that iterates over a vector and multiplies each element. Created by Adam, Ash, and Thomas.

### CODE REVIEW

**Review by mape0122 — DISMISSED** [review]
Need to remove the binary files (exe files)

**Review by p-lucero — COMMENTED** [review]
Mechanically, the code does what it should. An explanation of the tests that you wrote in the main function would be greatly helpful in making it more readable. Could also test edge cases (e.g. 0, negative numbers)

**Comment by adamtenhoeve** [comment]
Removed all the executable and .o files. Should be good now.

**Review by muzny — CHANGES_REQUESTED** [review]
remove my-new-branch-file

**Review by muzny — APPROVED** [review]

**Comment by muzny** [comment]
You're good to go once you resolve your merge conflicts you can merge to master!

**Comment by muzny** [comment]
To do this, go to your local master, pull so that it is up to date with remote master, then go to your local branch adam-ash-... and run a git merge master to merge master in. Resolve any merge conflicts, then push to remote adam-ash-.... follow this until the this branch has conflicts that must be resolved warning goes away!

**Pull request merged**
